# Generated by Django 4.0 on 2022-01-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_active_time_recipe_notes_recipe_servings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='public_id',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
