# Generated by Django 4.0 on 2022-01-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_public_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['public_id', 'slug'], name='recipes_rec_public__59482a_idx'),
        ),
    ]
