# Generated by Django 4.0.1 on 2022-01-12 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_tags'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='recipe',
            name='recipes_rec_public__59482a_idx',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='public_id',
        ),
    ]
